<?php
/**
 * QPOF — دادهٔ آمادهٔ اعمال (خودکار از روی ممیزی واقعی سایت ساخته شده؛ دست‌نویس نیست).
 * Generated by qp_fixdata.py — WordPress.2026-09-21qpedia.xml
 */
if ( ! defined( 'ABSPATH' ) ) { exit; }

function qpof_data() {
    static $cache = null;
    if ( $cache !== null ) { return $cache; }
    $cache = array(
        'stats' => array(            'link_fix_posts' => '10',
            'link_fix_hrefs' => '12',
            'draft_unlink_posts' => '',
            'draft_unlink_hrefs' => '',
            'meta_fill' => '1',
            'kw_fill' => '1',
            'feat_alt' => '',
            'redirect_301' => '40',
            'redirect_410' => '26',
            'redirect_review' => '1',),
        // اصلاح لینک شکسته: slug مقاله => array( href قدیمی => href جدید )
        'link_fixes' => array(
            'quantum-solipsism' => array('https://qpedia.ir/quantum-measurement-problem/' => 'https://qpedia.ir/quantum-measurement/', 'https://qpedia.ir/quantum-decoherence/' => 'https://qpedia.ir/decoherence/'),
            'quantum-fiction' => array('https://qpedia.ir/quantum-measurement-problem/' => 'https://qpedia.ir/quantum-measurement/', 'https://qpedia.ir/quantum-decoherence/' => 'https://qpedia.ir/decoherence/'),
            'wormhole' => array('https://qpedia.ir/quantum-entanglement/' => 'https://qpedia.ir/quantum-entanglement-explained/'),
            'quantum-droplet' => array('https://qpedia.ir/quantum-fluctuations/' => 'https://qpedia.ir/quantum-fluctuations-cosmos/'),
            'quantum-bounce' => array('https://qpedia.ir/loop-quantum-gravity/' => 'https://qpedia.ir/quantum-gravity/'),
            'slow-light' => array('https://qpedia.ir/quantum-decoherence/' => 'https://qpedia.ir/decoherence/'),
            'quantum-dimer' => array('https://qpedia.ir/quantum-entanglement/' => 'https://qpedia.ir/quantum-entanglement-explained/'),
            'cosmic-microwave-background' => array('https://qpedia.ir/dark-energy/' => 'https://qpedia.ir/dark-energy-quantum/'),
            'cosmic-inflation' => array('https://qpedia.ir/dark-energy/' => 'https://qpedia.ir/dark-energy-quantum/'),
            'dilution-refrigerator' => array('https://qpedia.ir/superconducting-qubit/' => 'https://qpedia.ir/superconductivity/'),
        ),
        // بازکردن لینک به‌پیش‌نویس: slug مقاله => array( href )
        'draft_unlinks' => array(

        ),
        // متا: slug مقاله => توضیح پیشنهادی (بازبینی انسانی توصیه می‌شود)
        'meta_fill' => array(
            'simon-algorithm' => 'تابعی داریم که دو ورودی را دقیقاً زمانی به یک خروجی می فرستد که اختلاف دودویی آن ها رشته پنهان s باشد. هدف یافتن s است. الگوریتم سایمون با نمونه گیری…',
        ),
        // کلیدواژهٔ کانونی: slug => عبارت پیشنهادی
        'kw_fill' => array(
            'simon-algorithm' => 'الگوریتم سایمون پیدا کردن دوره',
        ),
        // ALT تصویر شاخص: attachment_id => متن پیشنهادی
        'feat_alt' => array(

        ),
        // ریدایرکت‌ها: مسیر منبع => مقصد کامل (۳۰۱)
        'redirects_301' => array(
            '/quantum-measurement-problem/' => 'https://qpedia.ir/quantum-measurement/',
            '/quantum-decoherence/' => 'https://qpedia.ir/decoherence/',
            '/quantum-entanglement/' => 'https://qpedia.ir/quantum-entanglement-explained/',
            '/quantum-fluctuations/' => 'https://qpedia.ir/quantum-fluctuations-cosmos/',
            '/loop-quantum-gravity/' => 'https://qpedia.ir/quantum-gravity/',
            '/dark-energy/' => 'https://qpedia.ir/dark-energy-quantum/',
            '/superconducting-qubit/' => 'https://qpedia.ir/superconductivity/',
            '/scientists/albert-einstein/' => 'https://qpedia.ir/scientists/albert-einstein-2/',
            '/scientist/albert-einstein/' => 'https://qpedia.ir/scientists/albert-einstein-2/',
            '/albert-einstein/' => 'https://qpedia.ir/scientists/albert-einstein-2/',
            '/scientists/max-planck/' => 'https://qpedia.ir/scientists/max-plank/',
            '/scientist/max-planck/' => 'https://qpedia.ir/scientists/max-plank/',
            '/max-planck/' => 'https://qpedia.ir/scientists/max-plank/',
            '/epr-paradox-2/' => 'https://qpedia.ir/epr-paradox/',
            '/no-cloning-theorem-2/' => 'https://qpedia.ir/no-cloning-theorem/',
            '/quantum-gate-2/' => 'https://qpedia.ir/quantum-gate/',
            '/solvay-conference-1927-2/' => 'https://qpedia.ir/solvay-conference-1927/',
            '/aspect-experiment-1982-2/' => 'https://qpedia.ir/aspect-experiment-1982/',
            '/absolute-zero-2/' => 'https://qpedia.ir/absolute-zero/',
            '/alpha-decay-2/' => 'https://qpedia.ir/alpha-decay/',
            '/stimulated-emission-2/' => 'https://qpedia.ir/stimulated-emission/',
            '/neutrino-2/' => 'https://qpedia.ir/neutrino/',
            '/standard-model-2/' => 'https://qpedia.ir/standard-model/',
            '/virtual-particles-2/' => 'https://qpedia.ir/virtual-particles/',
            '/stern-gerlach-experiment-2/' => 'https://qpedia.ir/stern-gerlach-experiment/',
            '/flash-memory-2/' => 'https://qpedia.ir/flash-memory/',
            '/scanning-tunneling-microscope-2/' => 'https://qpedia.ir/scanning-tunneling-microscope/',
            '/fiber-optics-2/' => 'https://qpedia.ir/fiber-optics/',
            '/quantum-supremacy-2/' => 'https://qpedia.ir/quantum-supremacy/',
            '/shor-algorithm-2/' => 'https://qpedia.ir/shor-algorithm/',
            '/pilot-wave-2/' => 'https://qpedia.ir/pilot-wave/',
            '/genetic-mutation-2/' => 'https://qpedia.ir/genetic-mutation/',
            '/google-error-correction__trashed/' => 'https://qpedia.ir/quantum-error-correction/',
            '/higgs-boson-2/' => 'https://qpedia.ir/higgs-boson/',
            '/coherence-2/' => 'https://qpedia.ir/coherence/',
            '/grover-algorithm-2/' => 'https://qpedia.ir/grover-algorithm/',
            '/quantum-error-correction-2/' => 'https://qpedia.ir/quantum-error-correction/',
            '/bose-einstein-condensate-2/' => 'https://qpedia.ir/bose-einstein-condensate/',
            '/stellar-fusion-2/' => 'https://qpedia.ir/stellar-fusion/',
            '/quantum-simulation-2/' => 'https://qpedia.ir/quantum-simulation/',
        ),
        // پاسخ ۴۱۰ (حذف‌شده بدون جایگزین)
        'redirects_410' => array(
            '' => '/black-hole/',
            '1' => '/dark-matter/',
            '2' => '/fundamental-forces/',
            '3' => '/led/',
            '4' => '/matter-wave/',
            '5' => '/max-planck-blackbody/',
            '6' => '/noon-state/',
            '7' => '/quantum-art/',
            '8' => '/quantum-communication/',
            '9' => '/quantum-ethics/',
            '10' => '/quantum-game-theory/',
            '11' => '/quantum-interference/',
            '12' => '/quantum-investment/',
            '13' => '/quantum-key-distribution/',
            '14' => '/quantum-literacy/',
            '15' => '/quantum-photosynthesis/',
            '16' => '/quantum-policy/',
            '17' => '/quantum-smart-contract/',
            '18' => '/quantum-startup/',
            '19' => '/semiconductor/',
            '20' => '/swap-test/',
            '21' => '/transistor/',
            '22' => '/dirac-antimatter__trashed/',
            '23' => '/led__trashed/',
            '24' => '/max-planck-blackbody__trashed/',
            '25' => '/quantum-photosynthesis__trashed/',
        ),
        // جفت‌های ریدایرکت با شباهت متوسط — بازبینی انسانی
        'redirects_review' => array(
            'quantum-error-correction <== google-error-correction__trashed' => '0.61',
        ),
    );
    return $cache;
}
