<?php
/**
 * Plugin Name: Qpedia One-Time Importer Screenshot 1610 10
 * Description: به‌روزرسانی کنترل‌شده ده مقاله بازنویسی‌شده Qpedia با SEO، دسته‌بندی و FAQ Schema.
 * Version: 1.0.0
 * Author: Qpedia Editorial
 */
if (!defined('ABSPATH')) exit;
const QPSS1610_OPTION='qpedia_importer_screenshot_1610_10_completed';
add_action('admin_menu',function(){add_management_page('درون‌ریز ده مقاله Qpedia','درون‌ریز ده مقاله Qpedia','manage_options','qpedia-importer-screenshot-1610-10','qpss1610_page');});
function qpss1610_page(){if(!current_user_can('manage_options'))return;$done=get_option(QPSS1610_OPTION);echo '<div class="wrap" dir="rtl"><h1>درون‌ریز ده مقاله بازنویسی‌شده</h1>';if($done){echo '<div class="notice notice-success"><p>قبلاً در '.esc_html($done).' اجرا شده است.</p></div></div>';return;}if(isset($_POST['qpss1610_run'])){check_admin_referer('qpss1610_run');$r=qpss1610_run();$bad=false;foreach($r as $x)if(!$x['ok'])$bad=true;echo '<div class="notice '.($bad?'notice-warning':'notice-success').' "><ul>';foreach($r as $x)echo '<li>'.esc_html($x['message']).'</li>';echo '</ul></div>';if(!$bad){update_option(QPSS1610_OPTION,current_time('mysql'),false);echo '<p><strong>هر ده مقاله به‌روزرسانی شدند؛ افزونه را حذف کنید.</strong></p></div>';return;}}echo '<p>فقط نوشته‌های موجود را با ID یا slug به‌روزرسانی می‌کند. تاریخ انتشار، نویسنده و تصویر شاخص تغییر نمی‌کنند. ابتدا پشتیبان بگیرید.</p><form method="post">';wp_nonce_field('qpss1610_run');submit_button('اجرای به‌روزرسانی','primary','qpss1610_run');echo '</form></div>';}
function qpss1610_run(){$items=json_decode(file_get_contents(plugin_dir_path(__FILE__).'articles.json'),true);if(!is_array($items)||count($items)!==10)return [['ok'=>false,'message'=>'فایل داده معتبر نیست.']];$r=[];foreach($items as $i){$p=get_post((int)$i['post_id']);if(!$p||$p->post_type!=='quantum_article')$p=get_page_by_path(sanitize_title($i['slug']),OBJECT,'quantum_article');if(!$p){$r[]=['ok'=>false,'message'=>'پیدا نشد: '.$i['title']];continue;}$u=wp_update_post(['ID'=>$p->ID,'post_title'=>$i['title'],'post_name'=>$i['slug'],'post_content'=>$i['content']],true);if(is_wp_error($u)){$r[]=['ok'=>false,'message'=>$i['title'].': '.$u->get_error_message()];continue;}$meta=['rank_math_focus_keyword'=>$i['focus_keyword'],'rank_math_title'=>$i['seo_title'],'rank_math_description'=>$i['description'],'_qpedia_focus_keyphrase'=>$i['focus_keyword'],'_qpedia_seo_title'=>$i['seo_title'],'_qpedia_meta_description'=>$i['description'],'_yoast_wpseo_focuskw'=>$i['focus_keyword'],'_yoast_wpseo_title'=>$i['seo_title'],'_yoast_wpseo_metadesc'=>$i['description']];foreach($meta as $k=>$v)update_post_meta($p->ID,$k,$v);$t=$i['taxonomy'];$m=term_exists($t['mother_slug'],'quantum_category');if(!$m)$m=wp_insert_term($t['mother_name'],'quantum_category',['slug'=>$t['mother_slug']]);if(is_wp_error($m)){$r[]=['ok'=>false,'message'=>'خطای دسته: '.$i['title']];continue;}$mid=is_array($m)?(int)$m['term_id']:(int)$m;$c=term_exists($t['category_slug'],'quantum_category');if(!$c)$c=wp_insert_term($t['category_name'],'quantum_category',['slug'=>$t['category_slug'],'parent'=>$mid]);if(is_wp_error($c)){$r[]=['ok'=>false,'message'=>'خطای دسته: '.$i['title']];continue;}$cid=is_array($c)?(int)$c['term_id']:(int)$c;wp_set_object_terms($p->ID,[$mid,$cid],'quantum_category',false);$e=[];foreach($i['faqs'] as $f)$e[]=['@type'=>'Question','name'=>$f['question'],'acceptedAnswer'=>['@type'=>'Answer','text'=>$f['answer']]];$schema=['@context'=>'https://schema.org','@type'=>'FAQPage','mainEntity'=>$e];update_post_meta($p->ID,'rank_math_schema_FAQPage',$schema);update_post_meta($p->ID,'_qpedia_faq_schema',wp_json_encode($schema,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));clean_post_cache($p->ID);$r[]=['ok'=>true,'message'=>'به‌روزرسانی شد: '.$i['title'].' (ID '.$p->ID.')'];}return $r;}
