#!/usr/bin/env python3
"""داده‌های واژه‌نامه ۲۰۰ اصطلاحی — بخش یکم: تغییر نام‌ها و نقشهٔ مقالهٔ مرتبط (اصطلاح‌های ۱ تا ۱۰۰)."""

# اصطلاح‌هایی که در فهرست قدیمی عنوان بلند، تکراری یا نامناسب داشتند با اصطلاح دقیق‌تر جایگزین می‌شوند.
RENAMES = {
    'آیا فیزیک کلاسیک اشتباه است': ('حد کلاسیک', 'مرزی که در آن پیش‌بینی‌های فیزیک کلاسیک به‌قدر کافی دقیق می‌ماند'),
    'آیا هوش مصنوعی از کوانتوم استفاده می‌کند': ('کوانتوم‌واشینگ', 'به‌کاربردن واژهٔ کوانتوم در تبلیغ محصولی که سازوکار کوانتومی روشنی ندارد'),
    'فیبر نوری چگونه کار می‌کند': ('بازتاب کلی درونی', 'ماندن نور در محیط غلیظ‌تر هنگام برخورد با زاویه بزرگ‌تر از زاویه حد است'),
    'آیا جهش ژنتیکی کوانتومی است': ('فتوسنتز کوانتومی', 'بررسی نقش همدوسی و انتقال انرژی کوانتومی در نخستین گام‌های فتوسنتز'),
    'نور کند؛ کنترل سرعت گروهی بدون کندشدن ثابت بنیادی نور': ('پالس آتوثانیه', 'پالسی با کشش زمانی چند ده آتوثانیه که حرکت الکترون در اتم را قابل‌اندازه‌گیری می‌کند'),
    'انگشت‌نگاری کوانتومی؛ مقایسه داده با پیام بسیار کوتاه': ('پروتکل BB84', 'نخستین پروتکل عملی توزیع کلید کوانتومی که امنیت آن بر پایهٔ حالت‌های کوانتومی است'),
    'یخچال رقیق‌سازی؛ چگونه به چند میلی‌کلوین می‌رسیم': ('چاه کوانتومی', 'ساختار نازکی که حرکت الکترون را در یک راستا محدود و ترازهای گسسته ایجاد می‌کند'),
    'انرژی تاریک و جهان کوانتومی؛ چرا خلأ این‌قدر سبک است': ('ثابت کیهان‌شناسی', 'جمله‌ای در معادلات نسبیت عام که شتاب‌گرفتن انبساط جهان را توصیف می‌کند'),
    'داستان علمی‌تخیلی کوانتومی؛ مرز تخیل جذاب و علم واقعی': ('آزمایش فکری', 'سازه‌ای خیالی برای آزمودن منطقی یک نظریه، نه گزارشی از یک رویداد واقعی'),
    'تکینگی کوانتومی؛ مرز شکست نظریه یا جهش فرضی فناوری': ('مرز پلانک', 'مقیاسی که در آن آثار گرانش کوانتومی دیگر قابل چشم‌پوشی نیستند'),
    'کوانتوم در باکتری‌ها؛ از فتوسنتز تا حس‌کردن میدان': ('حس مغناطیسی', 'توانایی بعضی جانداران در استفاده از میدان مغناطیسی زمین برای مسیریابی'),
    'کوانتوم در ویروس‌ها؛ علم مولکولی یا برچسبی گمراه‌کننده': ('اثر هال کوانتومی', 'کوانتش هدایت‌پذیری جانبی در لایه‌های نازک زیر میدان مغناطیسی قوی'),
    'عایق توپولوژیک؛ درون عایق، روی سطح رسانا': ('گرافن', 'لایه‌ای تک‌اتمی از کربن با رفتار الکترونی غیرعادی و تحرک‌پذیری بالا'),
    'تلپورت کوانتومی': ('سرعت نور', 'بیشینهٔ سرعت انتقال انرژی و اطلاعات در فضازمان که هیچ پدیدهٔ کوانتومی آن را نقض نمی‌کند'),
}

# نقشهٔ قطعی هر اصطلاح به مقالهٔ مرتبط در qpedia.ir
SLUG_MAP = {
    'مکانیک کوانتومی': 'what-is-quantum',
    'فیزیک کوانتومی': 'quantum-physics-vs-quantum-mechanics',
    'کوانتش': 'energy-levels',
    'حالت کوانتومی': 'quantum-state',
    'تابع موج': 'wave-function',
    'دامنه احتمال': 'born-probability',
    'احتمال کوانتومی': 'quantum-probability',
    'برهم‌نهی کوانتومی': 'quantum-superposition',
    'درهم‌تنیدگی کوانتومی': 'quantum-entanglement-explained',
    'همدوسی کوانتومی': 'coherence',
    'واهمدوسی': 'decoherence',
    'اندازه‌گیری کوانتومی': 'quantum-measurement',
    'فروپاشی تابع موج': 'quantum-measurement',
    'ناظر کوانتومی': 'observer',
    'اصل عدم قطعیت': 'heisenberg-uncertainty-principle',
    'دوگانگی موج و ذره': 'wave-particle-duality',
    'تداخل کوانتومی': 'double-slit-experiment',
    'تونل‌زنی کوانتومی': 'quantum-tunneling',
    'اثر زنون کوانتومی': 'quantum-zeno-effect',
    'اصل مکملیت': 'complementarity-principle',
    'قضیه عدم شبیه‌سازی': 'quantum-simulation',
    'یکانی بودن': 'why-quantum-math-works',
    'تراز انرژی': 'energy-levels',
    'حالت پایه': 'quantum-state',
    'حالت برانگیخته': 'energy-levels',
    'اسپین کوانتومی': 'quantum-spin',
    'تکانه زاویه‌ای': 'quantum-number',
    'عدد کوانتومی': 'quantum-number',
    'ذره بنیادی': 'standard-model',
    'شبه‌ذره': 'superconductivity',
    'فوتون': 'photon',
    'الکترون': 'electron',
    'پوزیترون': 'antimatter',
    'پروتون': 'proton-neutron-quark-structure',
    'نوترون': 'proton-neutron-quark-structure',
    'نوترینو': 'neutrino',
    'کوارک': 'quark',
    'گلوئون': 'gluon-w-z-bosons',
    'بوزون': 'gluon-w-z-bosons',
    'فرمیون': 'pauli-exclusion-principle',
    'بوزون هیگز': 'higgs-boson',
    'پادماده': 'antimatter',
    'نابودی ماده و پادماده': 'pet-scan-antimatter',
    'مدل استاندارد': 'standard-model',
    'نیروی الکترومغناطیسی': 'quantum-electrodynamics',
    'نیروی هسته‌ای قوی': 'gluon-w-z-bosons',
    'نیروی هسته‌ای ضعیف': 'neutrino',
    'نظریه میدان کوانتومی': 'quantum-electrodynamics',
    'الکترودینامیک کوانتومی': 'quantum-electrodynamics',
    'خلأ کوانتومی': 'vacuum-fluctuations',
    'افت‌وخیز کوانتومی': 'quantum-fluctuations-cosmos',
    'انرژی نقطه صفر': 'zero-point-energy-scam',
    'اثر کازیمیر': 'casimir-effect',
    'ذره مجازی': 'virtual-particles',
    'ثابت پلانک': 'planck-constant',
    'طول موج دوبروی': 'wave-particle-duality',
    'آزمایش دو شکاف': 'double-slit-experiment',
    'نامساوی بل': 'bell-inequality',
    'آزمون بل': 'bell-experiments',
    'متغیر پنهان': 'pilot-wave',
    'واقع‌گرایی موضعی': 'bell-experiments',
    'تفسیر کپنهاگی': 'copenhagen-interpretation',
    'تفسیر جهان‌های متعدد': 'many-worlds-interpretation',
    'پارادوکس EPR': 'epr-paradox',
    'گربه شرودینگر': 'schrodinger-cat',
    'دوست ویگنر': 'wigner-friend',
    'کیوبیت': 'qubit',
    'کیوبیت فیزیکی': 'ibm-condor-processor',
    'کیوبیت منطقی': 'quantum-error-correction',
    'گیت کوانتومی': 'quantum-gate',
    'مدار کوانتومی': 'quantum-gate',
    'الگوریتم کوانتومی': 'shor-algorithm',
    'تصحیح خطای کوانتومی': 'quantum-error-correction',
    'کاهش خطای کوانتومی': 'topological-quantum-computing',
    'رایانش تحمل‌پذیر در برابر خطا': 'topological-quantum-computing',
    'عصر NISQ': 'nisq-era',
    'برتری کوانتومی': 'quantum-supremacy',
    'یادگیری ماشین کوانتومی': 'quantum-machine-learning',
    'کرنل کوانتومی': 'quantum-machine-learning',
    'حافظه کوانتومی': 'quantum-network',
    'تله‌پورت کوانتومی': 'quantum-teleportation',
    'توزیع کلید کوانتومی': 'quantum-cryptography-internet-security',
    'رمزنگاری پساکوانتومی': 'post-quantum-cryptography',
    'تکرارگر کوانتومی': 'quantum-network',
    'شبکه کوانتومی': 'quantum-network',
    'پیوند جوزفسون': 'josephson-junction',
    'جفت کوپر': 'superconductivity',
    'ابررسانایی': 'superconductivity',
    'ابرشارگی': 'superfluidity',
    'چگالش بوز–اینشتین': 'bose-einstein-condensate',
    'ماده کوانتومی': 'quantum-spin-liquid',
    'مایع اسپینی کوانتومی': 'quantum-spin-liquid',
    'عایق توپولوژیک': 'topological-insulator',
    'گرانش کوانتومی': 'quantum-gravity',
    'تابش هاوکینگ': 'black-hole-information-paradox',
    'افق رویداد': 'black-hole-information-paradox',
    'پارادوکس اطلاعات سیاه‌چاله': 'black-hole-information-paradox',
    'منحنی پیج': 'holographic-principle',
    'اصل هولوگرافیک': 'holographic-principle',
    'تورم کیهانی': 'cosmic-inflation',
    'اثر آهارونوف–بوهم': 'aharonov-bohm-effect',
    'کریستال‌درمانی': 'crystal-healing-debunked',
    'هوش مصنوعی کوانتومی': 'quantum-ai-marketing-hype',
    'اصل طرد پاولی': 'pauli-exclusion-principle',
    'حد کلاسیک': 'is-classical-physics-wrong',
    'تفسیر مکانیک کوانتومی': 'quantum-interpretation-debate',
    'کوانتوم‌واشینگ': 'quantum-hype-bubble',
    'میکروسکوپ تونلی روبشی': 'scanning-tunneling-microscope',
    'فیبر نوری': 'fiber-optics',
    'الگوریتم شور': 'shor-algorithm',
    'نظریه موج راهنما': 'pilot-wave',
    'جهش ژنتیکی کوانتومی': 'genetic-mutation',
    'لیدار کوانتومی': 'quantum-lidar',
    'نور کند': 'slow-light',
    'لیتوگرافی کوانتومی': 'quantum-lithography',
    'انگشت‌نگاری کوانتومی': 'quantum-fingerprinting',
    'یخچال رقیق‌سازی': 'dilution-refrigerator',
    'اکسیون': 'axion',
    'ویمپ': 'wimp',
    'انرژی تاریک و جهان کوانتومی': 'dark-energy-quantum',
    'تابش زمینه کیهانی': 'cosmic-microwave-background',
    'کرم‌چاله': 'wormhole',
    'کیهان‌شناسی کوانتومی': 'quantum-cosmology',
    'جهش کوانتومی کیهان': 'quantum-bounce',
    'موسیقی کوانتومی': 'quantum-music',
    'داستان علمی‌تخیلی کوانتومی': 'quantum-fiction',
    'فرهنگ کوانتومی': 'quantum-culture',
    'زمستان کوانتومی': 'quantum-winter',
    'تکینگی کوانتومی': 'quantum-singularity',
    'کوانتوم و سرطان': 'quantum-cancer',
    'کوانتوم در باکتری‌ها': 'quantum-bacteria',
    'کوانتوم در ویروس‌ها': 'quantum-viruses',
    'تابش شتاب و اثر اونرو': 'acceleration-radiation',
    'میکروسکوپ کوانتومی': 'quantum-microscopy',
    'رایانش کوانتومی ابری': 'quantum-cloud',
    'الگوریتم گروور': 'grover-algorithm',
    'قضیه عدم‌کپی کوانتومی': 'no-cloning-theorem',
    'شبیه‌سازی کوانتومی': 'quantum-simulation',
    'بازتاب کلی درونی': 'fiber-optics',
    'فتوسنتز کوانتومی': 'quantum-bacteria',
    'پالس آتوثانیه': 'attosecond-nobel-2023',
    'پروتکل BB84': 'quantum-cryptography-internet-security',
    'چاه کوانتومی': 'quantum-dots-displays',
    'ثابت کیهان‌شناسی': 'dark-energy-quantum',
    'آزمایش فکری': 'schrodinger-cat',
    'مرز پلانک': 'quantum-gravity',
    'حس مغناطیسی': 'quantum-navigation',
    'اثر هال کوانتومی': 'topological-insulator',
    'گرافن': 'transistor-quantum',
}
